### ISSUE TITLE
Admin Issue ezleague 

### ISSUE THREAD

**Issue by stevej891** [stoopkid1/ezleague#146]
after the update on a fresh install when i go to add user in admin it just shows a blank page

**Comment by stoopkid1** [comment]
@stevej891 are you clicking the "Run Database Upgrade" in the admin panel, or are you clicking the "run the update file" link at the top of the admin dashboard?

i'm trying to narrow down exactly how you updated. are you running v3.4.7?

**Comment by stoopkid1** [comment]
@stevej891 i just pushed a small update (v3.8.8). 
`admin/upgrade.php`
`admin/header.php`
`header.php`
those 3 files were updated. try re-downloading and only replacing those 3 files. please let me know if this fixes (or doesn't fix) your issue

**Comment by stevej891** [comment]
i updated by clicking run database upgrade and also my version is 3.47 but
it still saying i need to update

**Comment by stevej891** [comment]
not admin user its for regular user in the admin panel

**Comment by stevej891** [comment]
sorry didnt explain myself better

**Comment by stevej891** [comment]
i just updated the issue is still there it is under the admin panel when you go to users then you go to create account it is just a blank Page

**Comment by stoopkid1** [comment]
@stevej891 i never finished the "create account" page. only admin accounts can be created in the admin panel (site settings > admin users). non-admin users create their account from the main site (non-admin site).

closing this issue since there is no bug, but i do need to finish adding the "create user" feature at a later date
