### ISSUE TITLE
Tournament issues

### ISSUE THREAD

**Issue by hraki** [stoopkid1/ezleague#164]
I found some issues with the tournament.

1- When you generate the bracket he only generate the first match (the top of the bracket) the others stay blank.

2- When you assign maps to the rounds, he only save the map you assign to Round 1 the other map round get blank

3- You can only have one tournament created, when you try to create a new one, he don't save it on DB

**Comment by stoopkid1** [comment]
do you see the other matches being created in the *tournament_matches*
 table?

i need to see your error log in order to know what's going on. the
tournament feature was pretty well tested.

pm me your site link / admin login details so i can see if there are any JS
errors visible

On Fri, May 1, 2015 at 11:49 AM, hraki <notifications@github.com> wrote:

> I found some issues with the tournament.
>
> When you generate the bracket he only generate the first match (the top of
> the bracket) the others stay blank.
>
> And when you assign maps to the rounds, he only save the map you assign to
> Round 1 the other map round get blank
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stoopkid1/ezleague/issues/164>.
>



-- 
Michael Loring
Lead Web Applications Engineer
The Chicago Sun-Times Media Company

President
Loring Enterprises

cell:         773 870 5442
http://www.mdloring.com

**Comment by hraki** [comment]
I sent you an email with the details.

I test with a 1vs1 Tournament with 4 teams

Its like he don't generate new ID's for the table only have the 0
In the *tournament_matches* table I only see one match created

and if I create a second tournament he don't crate the tournament too in the *tournaments* table

**Comment by stoopkid1** [comment]
@hraki thank you for reporting this issue. an upgrade patch has been released.
https://github.com/stoopkid1/ezleague/pull/166
